name: "Deploy to Gist"
description: "📌 Deploy file to Github Gist."
author: "Exuanbo"
branding:
  icon: "upload-cloud"
  color: "green"
inputs:
  token:
    required: true
    description: "Set personal access token for updating gist."
  gist_id:
    required: true
    description: "Set id of the gist to be updated."
  gist_file_name:
    required: false
    description: "Set file name in the gist."
  file_path:
    required: true
    description: "Set path of the file to be deployed."
runs:
  using: "node12"
  main: "dist/index.js"
