name: "test"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Dump version
        run: |
          node -v
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Test build
        env:
          INPUT_TOKEN: ${{ secrets.TOKEN }}
        run: npm run all

  action-with-all-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test action
        uses: ./
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: e885afa349a0e5d1cfb408e46d6a37bc
          gist_description: "foo bar"
          gist_file_name: foo.bar
          file_path: ./__tests__/foo.bar

  action-with-minimum-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test action
        uses: ./
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: e885afa349a0e5d1cfb408e46d6a37bc
          file_path: ./__tests__/foo.bar
